const messageList = [
  "DTG 171230 DU R DU FROM INS VIKRANT TS TO INS KALVARI INFO NDI JK Proceed to rendezvous point Charlie by 1800 hrs AAA BT APR 171230 AR",
  "DTG 181100 DU P DU FROM INS SHIVALIK CONF TO INS KOLKATA INFO NVG JK Maintain radio silence until further orders AAA BT APR 181100 AR",
  "DTG 191200 DU O DU FROM NCC VIZAG UC TO NCC DELHI INFO NDI JK Initiate navigation drill sequence Charlie Delta Echo BT APR 191200 AR",
  "DTG 201300 DU F DU FROM INS CHILKA TS TO INS ANGRE INFO NDS JK Emergency broadcast protocol activated stop follow standard instructions AAA BT APR 201300 AR",
  "DTG 211400 DU R DU FROM NCC KOCHI TO NCC MUMBAI INFO NDI JK Conduct weekly semaphore signal test at 1600 hrs sharp AAA BT APR 211400 AR",
  "DTG 171230 DU R DU FROM INS ANGRE TS TO NCC KOCHI INFO NDI JK All cadets must report for signal training session at 0600 hours sharp on the parade ground AAA BT APR 171230 AR",
  "DTG 181400 DU P DU FROM INS CHILKA TS TO INS RAJALI INFO NVG JK Commence emergency repair protocol and report status by 1900 hours AAA BT APR 181400 AR",
  "DTG 191515 DU O DU FROM NCC VIZAG UC TO NCC MUMBAI INFO NDI JK Execute joint coastal surveillance drill as per instruction Bravo Charlie AAA BT APR 191515 AR",
  "DTG 200845 DU F DU FROM INS VIKRAMADITYA CONF TO INS SHIVALIK INFO NDS JK Immediate redeployment to sector Alpha initiated stop standby for new orders BT APR 200845 AR",
  "DTG 211100 DU R DU FROM NCC TRIVANDRUM TO NCC GOA INFO NVG JK Naval communication workshop rescheduled to 1500 hrs at HQ conference hall MIM attendance compulsory BT APR 211100 AR",
    "DTG 211400 DU R DU FROM NCC KOCHI TO NCC MUMBAI INFO NDI JK Conduct weekly semaphore signal test at 1600 hrs sharp AAA BT APR 211400 AR",
    "DTG 171230 DU P DU FROM INS VIKRANT TO INS KALVARI INFO NDI JK Proceed to rendezvous point Charlie by 1800 hrs AAA BT APR 171230 AR",
    "DTG 200900 DU F DU FROM NAVCOM EAST TO INS SHIVALIK INFO NVG JK Initiate emergency docking procedures immediately AAA BT APR 200900 AR",
    "DTG 221000 DU O DU FROM FLEET HQ TO INS KILTAN INFO NDS JK Commence ASW drill as per Fleet Op Order 04/25 AAA BT APR 221000 AR",
    "DTG 191200 DU R DU FROM NCC CHENNAI TO NCC DELHI INFO NDI JK Submit signal training report by 1500 hrs AAA BT APR 191200 AR",
    "DTG 180845 DU R DU FROM INS KOLKATA TO INS MYSORE INFO NVG JK Complete radar calibration before 1000 hrs AAA BT APR 180845 AR",
    "DTG 151130 DU P DU FROM FLEET HQ TO INS SHAKTI INFO NDS JK Replenishment at sea scheduled for 1600 hrs AAA BT APR 151130 AR",
    "DTG 140915 DU R DU FROM NAVCOM WEST TO INS KAVARATTI INFO NVG JK Confirm status of communications equipment AAA BT APR 140915 AR",
    "DTG 230700 DU F DU FROM INS KORMA TO INS SUNAYNA INFO NDI JK Emergency evacuation drill begins at 0800 hrs sharp AAA BT APR 230700 AR",
    "DTG 121000 DU O DU FROM NCC LUCKNOW TO NCC BHOPAL INFO NDI JK Participate in all-India naval quiz round 2 AAA BT APR 121000 AR",
    "DTG 101500 DU R DU FROM FLEET HQ TO INS BETWA INFO NDS JK Send updated crew manifest by 1800 hrs AAA BT APR 101500 AR",
    "DTG 091430 DU P DU FROM INS TARKASH TO INS TRIKAND INFO NVG JK Begin missile loading drill at 1600 hrs AAA BT APR 091430 AR",
    "DTG 250945 DU R DU FROM NAVCOM SOUTH TO INS AIRAVAT INFO NDS JK Report weather anomaly over patrol route AAA BT APR 250945 AR",
    "DTG 260800 DU O DU FROM FLEET HQ TO INS KAMORTA INFO NDI JK Engage in high-speed maneuvering exercise AAA BT APR 260800 AR",
    "DTG 270730 DU F DU FROM NCC VISAKHAPATNAM TO NCC CHANDIGARH INFO NDI JK Conduct distress flag signaling test AAA BT APR 270730 AR",
    "DTG 280600 DU R DU FROM NAVCOM WEST TO INS VIRAAT INFO NDS JK Begin maintenance of radio antennas AAA BT APR 280600 AR",
    "DTG 290500 DU P DU FROM INS GHARIAL TO INS MAGAR INFO NVG JK Joint beach landing ops scheduled for 1000 hrs AAA BT APR 290500 AR",
    "DTG 300400 DU O DU FROM FLEET HQ TO INS SATPURA INFO NDI JK Test underwater sonar equipment before dive AAA BT APR 300400 AR",
    "DTG 010300 DU F DU FROM NCC JAIPUR TO NCC PATNA INFO NDI JK Prepare cadets for annual signal proficiency test AAA BT MAY 010300 AR",
    "DTG 021600 DU R DU FROM INS SHARDUL TO INS SUJATA INFO NDS JK Refit inspection due 1730 hrs today AAA BT MAY 021600 AR",
   
  ];


